---
title: Little App Workshop
---

*Philosophy of StatPREP Workshop**

* The first theme is an introduction to the philosophy of StatPREP and several of the Little Apps that can be used to demonstrate datacentric ideas to your students. This two-day workshop will be offered twice: first on Thursday, June 10, and Friday, June 11, and second on Friday, July 9, and Saturday, July 10.

* The plan for this StatPREP intro workshop is to have presentations on what it means to have your statistics class be datacentric, and the philosophy behind the ASA’s GAISE statement. There will be hands-on activities on using some of the activities written for the Little Apps, and time for small group discussions.

*At the end of the first day there will be time for socializing, and the second day starts with a social hour. The idea is to create a community of instructors who can ask each other for advice. If you are new to teaching statistics or have been teaching for awhile but would like to add more life to your statistics
course, this is a great workshop to attend to learn how to incorporate data into your course and be exposed to the StatPREP material.
