---
title: 2022 StatPREP Workshops
---

**Summer 2022 workshop is offered at Florida Southwestern State College in Fort Myers, FL**

**The workshop is offered on Friday, May 20 through Saturday, May 21.**

Host: Rona Axelrod, email is Rona.Axelrod@fsw.edu

**Logisitics for the traveling to the workshop**

Airport Information: Southwest Florida International Airport (RSW)

**Hotel Information:** A block of 30 rooms has been reserved at the Hilton Garden Inn in Fort Myers. Guests have until Monday, April 18, 2022 to make their reservation and get the group rate. The group rate is available for the nights May 16th through May 24th, and is \$104. You can either use the link [Hilton Garden Inn Fort Myers](www.fortmyers.stayhgi.com) and use the group code SPW. You can also call the Hilton Garden Inn Fort Myers at 239.790.3500, and ask for the StatPREP workshop group rate.

**Campus Information:** Location of the workshop on the Florida Southwestern State College Campus in the “U” Building, which located in the southwest corner of campus.  Use Parking Lot 11. No parking permmit is needed.

**Schedule of workshop:** Check back for schedule of the workshop.

**Registering for workshop:** To register for the workshop, please visit the link on [how to apply](https://maa.org/statprep#Apply).

**COVID Protocols at the Workshop**
The MAA and StatPREP leadership team are committed to providing a safe and healthy environment for all workshop attendees. All mandates outlined by Florida SouthWestern State College at the time of the workshop will be in effect and enforced during the conference. As these mandates are ever-changing, the MAA is closely monitoring them and will update registrants of requirement changes prior to the conference.


