---
title: 2021 StatPREP Workshops
---

**Summer 2021 workshops were offered in June and July. Below is a description of the workshops. The material for each workshop is still available at the links following the descriptions.**

* The first theme was an introduction to the philosophy of StatPREP and several of the Little Apps that can be used to demonstrate datacentric ideas to your students. This two-day workshop was offered twice: first time was on Thursday, June 10, and Friday, June 11, and second time was on Friday, July 9, and Saturday, July 10. 
[Link to Google Slides for Day 1](https://docs.google.com/presentation/d/16q-gzizzEgQEEwYSy2aSlHFIWVMrMWZGnOvljCY9QK4/edit?usp=sharing)

[Link to Google Slides for Day 2](https://docs.google.com/presentation/d/1xNZHsST-Dh9fnsETMDWHl-AGKCiLuwbaQPTfLnhfKkY/edit?usp=sharing)

* The second workshop theme was an Introduction to RStudio. GAISE stresses the idea of using real data, large datasets, and deemphasizing formulas. The best way to follow these guidelines is to use statistical software. One advantage of RStudio is that it is free for students, teachers, and institutions to use. This workshop introduced participants to the basics of RStudio with no prior knowledge of RStudio expected. The two-day workshop was offered twice: first time was on Friday, June 18, and Saturday, June 19, and second time was on Thursday, July 15, and Friday, July 16. Materials presented at the workshop can be access using the following Google slides.
[Link to Google Slides for Day 1](https://docs.google.com/presentation/d/1HMZGYCiIBi6bwQiqzO_bp9U4OEUlkjmYwq-ywGPvl20/edit?usp=sharing)

[Link to Google Slides for Day 2](https://docs.google.com/presentation/d/1JEAzI5XSM15CYkzuyl2ZhPsjv6SKBS1JGDkFeyVjk8M/edit?usp=sharing)

* An Intermediate/Advanced RStudio workshop was offered for those who have some experience with RStudio and wanted to learn more. This workshop exposed the attendee to some of the more sophisticated commands of RStudio. The Intermediate/Advance RStudio workshop was offered on Thursday, June 24 through Friday, June 25, and again was offered on Friday, July 23 through Saturday, July 24. Materials presented at the workshop can be access using the following Google slides.
[Link to Google Slides for Day 1](https://docs.google.com/presentation/d/1X6u_NYmOVMRCqgV3LnubeXIKRWdFRk4AB_WM04uMK9s/edit?usp=sharing)

[Link to Google Slides for Day 2](https://docs.google.com/presentation/d/1evn8GgmJ1hwBT-b9kQ2bmVvhxASePMzS_PEtEy6NLbo/edit?usp=sharing)

* You may be contemplating creating a data science program at your institution, but you are not sure where to start. A one-day workshop workshop featured a panel discussion with several people who have created data science programs at their institutions. The focus was on community colleges because of the unique issue that community college faces with articulation and workforce development. However, all institution types could gain some insights to create a program at their institution, so all faculty at any college or university are invited to review the material and watch the recordings This one day workshop was offered on Friday, June 4, and repeated on Saturday, July 31. 

Materials presented at the workshop can be access using the following Google slides.

[Link to Google slides](https://docs.google.com/presentation/d/1AO-DfCBmlvzeShNTZqhXrSgYv5_k3CC32DB0Sb8LMZU/edit?usp=sharing)

The recording of the June 4th panel discussion is available at the following links.

[June 4th recording](https://maa.zoom.us/rec/share/hPLEApbpQknlEd7EIHuAPa9Gazt5WE4bnZPUILKNyrhLpjwb25c4-bOP3rnP9b6q.9SCvRGuMQdFSyMpD)

The recording of the July 31st panel discussion is available is at the following link.

[July 31st recording](https://maa.zoom.us/rec/share/rO3xTlEtZHXFovxwu5ntVcKtMk3J1fsOR6fg0-PxhBgn_0cJHRl3FM8tW7Y4_kZc.IOvleAFixxFbOtI7)
