# Curricular Guide: OpenIntro Statistics, Diez et al., 4th edition

The book is online and available [here](https://www.openintro.org/book/os/).

This document is keyed to the table of contents of the book. 


## 1 Introduction to data

- 1.1 Case study: using stents to prevent strokes
- 1.2 Data basics 
    - Activity: [Response and Explanatory Variables](http://www.statprep.org/LittleAppSite/posts/Activities/Response_and_explanatory/)
    
- 1.3 Sampling principles and strategies 
- 1.4 Experiments 
    
    - Activity: [Sampling Bias and the Confidence Interval](http://www.statprep.org/LittleAppSite/posts/Activities/Sampling_bias/)
    - Acitivy: [Intervention and Prediction]( http://www.statprep.org/LittleAppSite/posts/Activities/Intervention_and_prediction/)
    
[Extended comments](comments_openintro.html#Chap1)

## 2 Summarizing data

- 2.1 Examining numerical data 
    - Activity: [Data and Point Plots](http://www.statprep.org/LittleAppSite/posts/Activities/Point_plots/)
    - Activity: [Shapes of distributions](http://www.statprep.org/LittleAppSite/posts/Activities/Distribution_shapes/)
- 2.2 Considering categorical data 
    - Activity: [Data and Point Plots](http://www.statprep.org/LittleAppSite/posts/Activities/Point_plots/)
- 2.3 Case study: malaria vaccine 

[Extended comments](comments_openintro.html#Chap2)

## 3 Probability 

- 3.1 Defining probability 
- 3.2 Conditional probability 
- 3.3 Sampling from a small population 
- 3.4 Random variables 
- 3.5 Continuous distributions 

[Extended comments](comments_openintro.html#Chap3)

## 4 Distributions of random variables

- 4.1 Normal distribution 
    - Activity: [Parameters and the Normal Distribution](http://www.statprep.org/LittleAppSite/posts/Activities/Normal_parameters/)
    - Activity[Common, Uncommon, and Rare](http://www.statprep.org/LittleAppSite/posts/Activities/Common_and_rare/)
- 4.2 Geometric distribution 
- 4.3 Binomial distribution 
- 4.4 Negative binomial distribution 
- 4.5 Poisson distribution 

[Extended comments](comments_openintro.html#Chap4)

## 5 Foundations for inference 

- 5.1 Point estimates and sampling variability
    - Activity: [What is a Confidence Interval](http://www.statprep.org/LittleAppSite/posts/Activities/What_is_a_confidence_interval/)
    - Activity: [Sampling Bias and the Confidence Interval](http://www.statprep.org/LittleAppSite/posts/Activities/Sampling_bias/)
- 5.2 Confidence intervals for a proportion 
- 5.3 Hypothesis testing for a proportion 

[Extended comments](comments_openintro.html#Chap5)

## 6 Inference for categorical data 

- 6.1 Inference for a single proportion 
- 6.2 Difference of two proportions 
- 6.3 Testing for goodness of fit using chi-square 
- 6.4 Testing for independence in two-way tables 

[Extended comments](comments_openintro.html#Chap6)

## 7 Inference for numerical data 

- 7.1 One-sample means with the t-distribution 
- 7.2 Paired data 
    - Activity: [Comparing Two Confidence Intervals](http://www.statprep.org/LittleAppSite/posts/Activities/Comparing_confidence_intervals/)
    - Activity: [Comparing Two Groups](http://www.statprep.org/LittleAppSite/posts/Activities/Comparing_two_groups/)
- 7.4 Power calculations for a difference of means 
- 7.5 Comparing many means with ANOVA 

[Extended comments](comments_openintro.html#Chap7)

## 8 Introduction to linear regression 

- 8.1 Fitting a line, residuals, and correlation 
     - Activity: [Introducing Linear Regression](http://www.statprep.org/LittleAppSite/posts/Activities/Introducing_linear_regression/)
     - Activity: [Describing Relationship Patterns in Words and Numbers](http://www.statprep.org/LittleAppSite/posts/Activities/Relationship_patterns/)
     - Activity: [How much is explained?](http://www.statprep.org/LittleAppSite/posts/Activities/How_much_is_explained/)
- 8.2 Least squares regression 
- 8.3 Types of outliers in linear regression 
- 8.4 Inference for linear regression 

[Extended comments](comments_openintro.html#Chap8)

## 9 Multiple and logistic regression

- 9.1 Introduction to multiple regression 
     - Activity: [Introducing Linear Regression](http://www.statprep.org/LittleAppSite/posts/Activities/Introducing_linear_regression/)
     - Activity: [Describing Relationship Patterns in Words and Numbers](http://www.statprep.org/LittleAppSite/posts/Activities/Relationship_patterns/)
- 9.2 Model selection 
- 9.3 Checking model conditions using graphs 
- 9.4 Multiple regression case study: Mario Kart 
- 9.5 Introduction to logistic regression 

[Extended comments](comments_openintro.html#Chap9)
