# OpenIntro Statistics (e/4)

The book is online and available [here](https://www.openintro.org/book/os/).

This document is keyed to  the table of contents of the book. 


## 1 Introduction to data

- 1.1 Case study: using stents to prevent strokes
- 1.2 Data basics 
    - Activity: [Types of Variables](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-variable-types/)
    - Activity: [Variables and the Units of Observation](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-variables-and-units/)
    - Activity: [Response and Explanatory Variables](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-response-and-explanatory/)
    - [Orientation](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-intervention-and-prediction/)
- 1.3 Sampling principles and strategies 
- 1.4 Experiments 
    - Activity: [Intervention and Prediction](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-intervention-and-prediction/)
    - Activity: [Experiment and causality](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-experiment-and-causality/)
    
[Extended comments](comments_openintro.html#Chap1)

## 2 Summarizing data

- 2.1 Examining numerical data 
    - Activity: [Jittering](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-jittering/)
    - Activity: [Shapes of distributions](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-distribution-shapes/)
    - Activity: [The Standard Deviation and the 95% Summary Interval](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-sd-and-summary-interval/)
    - Activity: [Variation and the 95% Summary Interval](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-summary-interval/)
- 2.2 Considering categorical data 
    - Activity: [Data and Point Plots](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-point-plot/)
- 2.3 Case study: malaria vaccine 

[Extended comments](comments_openintro.html#Chap2)

## 3 Probability 

- 3.1 Defining probability 
- 3.2 Conditional probability 
- 3.3 Sampling from a small population 
- 3.4 Random variables 
- 3.5 Continuous distributions 

[Extended comments](comments_openintro.html#Chap3)

## 4 Distributions of random variables

- 4.1 Normal distribution 
    - Activity: [Shapes of Distributions](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-distribution-shapes/)
    - Activity: [Parameters and the Normal Distribution](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-normal-parameters/)
    - Activity[Common, Uncommon, and Rare](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-common-and-rare/)
- 4.2 Geometric distribution 
- 4.3 Binomial distribution 
- 4.4 Negative binomial distribution 
- 4.5 Poisson distribution 

[Extended comments](comments_openintro.html#Chap4)

## 5 Foundations for inference 

- 5.1 Point estimates and sampling variability
    - Activity: [What is a Confidence Interval](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-what-is-a-confidence-interval/)
    - Activity: [Sampling Bias and the Confidence Interval](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-sampling-bias/)
- 5.2 Confidence intervals for a proportion 
- 5.3 Hypothesis testing for a proportion 

[Extended comments](comments_openintro.html#Chap5)

## 6 Inference for categorical data 

- 6.1 Inference for a single proportion 
- 6.2 Difference of two proportions 
- 6.3 Testing for goodness of fit using chi-square 
- 6.4 Testing for independence in two-way tables 

[Extended comments](comments_openintro.html#Chap6)

## 7 Inference for numerical data 

- 7.1 One-sample means with the t-distribution 
- 7.2 Paired data 
    - Activity: [The Two-Sample T-test](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-two-sample-t-test/)
    - Activity: [Comparing Two Confidence Intervals](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-comparing-confidence-intervals/)
    - Activity: [Comparing Two Groups](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-comparing-two-groups/)
- 7.3 Difference of two means 
    - Activity: [The Two-Sample T-test](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-two-sample-t-test/)
    - Activity: [Comparing Two Confidence Intervals](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-comparing-confidence-intervals/)
- 7.4 Power calculations for a difference of means 
- 7.5 Comparing many means with ANOVA 

[Extended comments](comments_openintro.html#Chap7)

## 8 Introduction to linear regression 

- 8.1 Fitting a line, residuals, and correlation 
    - Activity: [Introducing Linear Regression](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-introducing-linear-regression/)
    - Activity: [Describing Relationship Patterns in Words and Numbers](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-relationship-patterns/)
    - Activity: [How much is explained?](https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-how-much-is-explained/)
- 8.2 Least squares regression 
- 8.3 Types of outliers in linear regression 
- 8.4 Inference for linear regression 

[Extended comments](comments_openintro.html#Chap8)

## 9 Multiple and logistic regression

- 9.1 Introduction to multiple regression 
    - Little App activity: Introducing Linear Regression: https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-introducing-linear-regression/
    - Discribing Relationship Patterns in Words and Numbers: https://ecstatic-mclean-a0b3e0.netlify.com/blog/activity-relationship-patterns/
- 9.2 Model selection 
- 9.3 Checking model conditions using graphs 
- 9.4 Multiple regression case study: Mario Kart 
- 9.5 Introduction to logistic regression 

[Extended comments](comments_openintro.html#Chap9)
