---
title: "Interesting Times in Statistics Education"
description: |
  Pre-COVID musings on trends in statistics education. Appearing in the April 1st, 2020 edition of <em>AMSTAT News</em>, it was <strong>not</strong> intended to be an April 1st joke. And yet ... The essay was written in December 2019 and publication was anticipated for Feb. 2020. Starting around April 1, COVID-19 became the dominant fact of life for statistics instructors (and everybody else in the world).  My sincere apologies for any offense that I might have given readers.  I regret that I didn’t keep better track of the changing publication schedule and update the essay accordingly.
  
author:
  - name: Daniel Kaplan
    url: kaplan@macalester.edu
    affiliation: Macalester College
date: 04-01-2020
preview: calvin.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

This article appeared originally [here](https://magazine.amstat.org/blog/2020/04/01/statprep-intro-stat-ed/) in the AMSTAT News. 

Daniel Kaplan, Macalester College

**Living in Interesting Times in Statistics Education**

These are interesting times in statistics education. As with the proverb, living in interesting times can be both blessing and curse.

The last decade has seen the emergence of data science as an organizing theme for extracting information from data. Some claim data science is merely a rebranding of statistics, a position that doesn’t withstand scrutiny. We face a genuine need to collaborate, an unnatural position for many academics. Our colleagues in computer science education need to acknowledge that they are often naïve with respect to statistics and the statistics education community accept that decision-making—the root of the demand for data science—is closely aligned with Bayesian thinking.

The last decade has also brought the emergence of randomization-based inference as a mainstream approach to teaching. This is a wonderful opportunity to enhance student understanding of inference, but requires careful rethinking of the traditional algebra-based curriculum.

Two other developments can be bewildering to educators. Prompted by the "crisis" in reproducibility, and in the face of a century of conflict about an appropriate basis for statistical inference, the American Statistical Association issued a statement in 2016 about p-values, calling for a course correction toward a "post p < 0.05 world." Ideas are starting to emerge about how to respond. For instance, Jeff Witmer proposed replacing the technical word "significant" with "discernible," avoiding the misleading confusion of "significant" with its everyday meaning.

Still another important development, modern causal inference, is unknown to the vast majority of statistical educators. It conflicts with the central mantra of introduction to statistics—“correlation is not causation”—and calls for tools for dealing with confounding that are alien to the traditional t-test course.

A challenge that must be met before we can respond completely to the previous developments is the crawling pace of the integration of modern computing into the statistics education curriculum. The computer is the essential tool in all areas of the economy, science, and government and the foundation of data science. Yet it’s commonplace for introduction to statistics students to see only graphing calculators, a limited and obsolete appliance widely found in algebra courses but in no other place in professional work or education.

The [StatPREP initiative](StatPREP.org), funded by the National Science Foundation, is a collaboration of the Mathematical Association of America (MAA), American Mathematical Association of Two-Year Colleges (AMATYC), and the ASA. StatPREP works to help introductory statistics instructors overcome the challenges of change. Only about 1–2 percent of statistics instructors can participate in StatPREP summer faculty-development workshops, although the StatPREP materials are available to anyone.

Through the StatPREP project, we have learned a lot about the obstacles to change. Not least among these are the many statistics instructors who have no training and no professional contact with statistics beyond the introductory course. Another is the sprawling historical development of the introductory course balkanizing the central inferential concepts into a series of historically contingent settings. A randomization curriculum can provide unity. But facing the simultaneous challenges of requiring a transition to computing and introducing a new paradigm, the authors of leading textbooks have sensibly decided to stick to the balkanized settings.

StatPREP.org is highly computationally oriented, so it may seem a surprise that we are also exploring an alternative strategy: minimizing computation, retaining formulas, but unifying inference. Our new short book, [*A Compact Guide to Classical Inference*](https://dtkaplan.github.io/CompactInference/), brings all the traditional inference settings of introductory statistics into a common framework: simple modeling and a single test statistic introduced in a novel, streamlined manner. We are literally "F-ing up statistics." Some may see "F-ing" as referring to something other than Fisher’s eponymous statistic, particularly since we dispense with the extensive probability tables still found in most textbooks. But we propose the substantial gains are worth the tiny loss.

The [*Compact Guide*](https://dtkaplan.github.io/CompactInference/) is not a textbook. First, it is solely about inference. Second, it is a guide for instructors, not students. We hope the book can help instructors see a path forward from the traditional course and toward one that can properly embrace covariation, computing, and data.

Take a look at StatPREP.org and share your thoughts with us. You may find Compact Guide illuminating or utterly confounding. Whichever, it is an honest attempt to respond to the interesting times in which we live.







